### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by f103mirage** [sjdirect/abotx#16] opened 2018-01-29 13:08 UTC
the UA works correctly on ABOT, but in ABOTX it not working correctly

**Comment by sjdirect** [comment] 2018-01-29 16:11
Tested both by xml config and setting on config object directly. Unable to reproduce. Can you give more info?

**Comment by f103mirage** [comment] 2018-01-30 12:18
I setup userAgentString in app.config AS **Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)**

ABOT use this user agent, but ABOTX when crawling ajax pages use another user agent: **Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1**

**Comment by sjdirect** [comment] 2018-02-02 20:50
Just deployed version 1.3.63 which should address this issue. Can you verify please?

**Comment by f103mirage** [comment] 2018-02-03 18:40
perfect... thanks

**Comment by sjdirect** [comment] 2018-02-05 20:03
Thanks for verifying. closing...

**Closed by sjdirect** 2018-02-05 20:03 UTC
