### ISSUE TITLE
Error when Inititalizing CrawlerX/ParallelCrawlEngine (System.FormatException)

### ISSUE THREAD

**Issue by ironman1984** [sjdirect/abotx#1] opened 2015-11-21 14:51 UTC
I have configured as guided in address but still appeared http://abotx.org/Learn/Configuration An unhandled exception of type 'error' System.FormatException 'print lỗi mscorlib.dll

Additional information: The datetime represented by the string is out of range.

when I initialize paragraph following command:
var crawler = new CrawlerX();//Errror when Init object CrawlerX
Here is the configuration in my app.config file:
<Configuration>
  <ConfigSections>
    <Section name = "abotX" type = "AbotX.Core.AbotXConfigurationSectionHandler, AbotX" />
    <Section name = "abot" type = "Abot.Core.AbotConfigurationSectionHandler, abot" />
  </ ConfigSections>
  <Abot>
    <CrawlBehavior
      maxConcurrentThreads = "10"
      maxPagesToCrawl = '1000'
      maxPagesToCrawlPerDomain = "0"
      maxPageSizeInBytes = "1048576"
      userAgentString = "Mozilla / 5.0 (Windows NT 6.3; Trident / 7.0; rv: 11.0), like Gecko"
      crawlTimeoutSeconds = "10"
      downloadableContentTypes = "text / html"
      isUriRecrawlingEnabled = "false"
      isExternalPageCrawlingEnabled = "false"
      isExternalPageLinksCrawlingEnabled = "false"
      httpServicePointConnectionLimit = "200"
      maxMemoryUsageInMb = "0"
      maxMemoryUsageCacheTimeInSeconds = "0"
      maxCrawlDepth = '1000'
      isForcedLinkParsingEnabled = "false"
      maxRetryCount = "0"
      minRetryDelayInMilliseconds = "0" />
    <Politeness
      isRespectRobotsDotTextEnabled = "false"
      isRespectMetaRobotsNoFollowEnabled = "false"
      isRespectAnchorRelNoFollowEnabled = "false"
      robotsDotTextUserAgentString = "abotagent"
      maxRobotsDotTextCrawlDelayInSeconds = "5"
      minCrawlDelayPerDomainMilliSeconds = "0" />
    <ExtensionValues>
      <Add key = "Key1" value = "value1" />
      <Add key = "key2" value = "value2" />
    </ ExtensionValues>
  </ Abot>
  <AbotX
    maxConcurrentSiteCrawls = "10"
    sitesToCrawlBatchSizePerRequest = "25"
    minSiteToCrawlRequestDelayInSecs = "15"
    isJavascriptRenderingEnabled = "false"
    javascriptRenderingWaitTimeInMilliseconds = "3500"
    />
</ Configuration>

You can send me an example using AbotX.

Thanks

**Comment by sjdirect** [comment] 2015-11-21 16:22
Hi, your config example above has all kinds of problems. Not sure if its github's markdown not displaying it correctly or if you got mixed up trying to put it together. Can you attach your app.config file to this thread instead of just pasting it in. 

I just verified the http://abotx.org/Learn/Configuration page config works on a new project.

**Comment by sjdirect** [comment] 2015-11-21 16:28
I just saw your last email had the app.config attached. I was able to copy and paste that config right in and didn't have any issues running AbotX. This is how my console app looks...

    class Program
    {
        static void Main(string[] args)
        {
            XmlConfigurator.Configure();
            var crawler = new CrawlerX();
            crawler.Crawl(new Uri("http://wvtesting2.com/"));
        }
    }

Like i mentioned i just pasted your app.config into the app.config and everything just worked. 

[App.config.txt](https://github.com/sjdirect/abotx/files/40878/App.config.txt)

**Comment by ironman1984** [comment] 2015-11-22 00:16
I have used above file App.config.txt and create a Console Application and build with NET Framework 4.0  but problems occur:

I have attached image file error:
![error abotx2](https://cloud.githubusercontent.com/assets/15957048/11321216/d6f2b76e-90e8-11e5-969d-3d7a09ff32f2.png)


Error to appear on Visual 2012, 2013 and 2015

Please help me check problem 

Thanks

**Comment by ironman1984** [comment] 2015-11-22 00:25
issues related to license?
I have installed NuGet and I want to use basic License. Where can I find the license or activation license file in basic mode.

I want to use the function ParallelCrawlerEngine

**Comment by sjdirect** [comment] 2015-11-22 04:24
Basic does not need a license file. I'm unable to reproduce this. Can you zip up simple solution reproduces this and attach it here? 

Reopening this issue. Did you accidentally close this issue?

**Comment by ironman1984** [comment] 2015-11-22 13:41
I found a cause related to license issues (not found find file AbotX.lic). If I use beta license, there is no error, but I can not use the function ParallelCrawlerEngine.

I do not understand why when I installed NuGet but related to license issues, while free license does not require file AbotX.lic

Thanks

**Comment by sjdirect** [comment] 2015-11-22 15:17
The ParallelCrawlerEngine license check bug should be fixed now. That package should be available on nuget if you update to the latest. Can you verify that this fixes your issues please?

**Comment by sjdirect** [comment] 2015-11-25 22:34
I am assuming this fixed your issue.

**Comment by sjdirect** [comment] 2015-12-19 06:27
Others are reporting issues related to this. Reopening to investigate with different versions of visual studio even though this user says they even see it in vs 2015.

**Comment by sjdirect** [comment] 2015-12-19 06:28
Some other users of visual studio 2013 are reporting this issue when running. Created a [sample project](https://github.com/sjdirect/abotx-basic-demo) to rule out user configuration errors. One customer reported not being able to build/run [forum discussion](https://groups.google.com/forum/#!topic/abot-web-crawler/EiznWedeQM8)

**Comment by sjdirect** [comment] 2015-12-19 06:32
Please feel free to keep replying to this thread with info on what versions of visual studio work and dont work with the [sample project](https://github.com/sjdirect/abotx-basic-demo).

**Comment by sjdirect** [comment] 2015-12-19 07:23
Ran the sample project with vs 2012 update 4 and had no issue or exceptions like reported by users. Will continue trying other versions.
![vs2012u4](https://cloud.githubusercontent.com/assets/3812834/11911982/745b51f2-a5e6-11e5-9ecf-f7bb0652f4de.png)

**Comment by sjdirect** [comment] 2015-12-19 07:29
Also if anyone could get me some stack traces or inner exceptions that would help. Also a screenshot of the visual studio about window like the one above so I can see exact versions as well. Thanks!

**Comment by sjdirect** [comment] 2015-12-19 19:54
Ran the sample project with vs 2013 premium 4 and had no issue or exceptions like reported by users. I'm going to leave this open. However, I need some help narrowing down specific versions of visual studio and .net to see if we can narrow this down further.
![vs2013prem](https://cloud.githubusercontent.com/assets/3812834/11914973/61aef5cc-a64f-11e5-9eaa-e5ad2cea2c77.png)

**Comment by Hajuddin** [comment] 2015-12-20 06:47
Please check the attached screen shots for more details. I'm still having the same issue.

![image](https://cloud.githubusercontent.com/assets/8736524/11916829/8c893486-a70f-11e5-947c-c55c1f726162.png)

![image](https://cloud.githubusercontent.com/assets/8736524/11916834/c9129384-a70f-11e5-9b0e-774c8adc56ee.png)

![image](https://cloud.githubusercontent.com/assets/8736524/11916836/dd605aec-a70f-11e5-86d9-4932fb966875.png)

My configuration is same as in the tutorial under "Full Configuration Example"
https://abotx.org/Learn/Configuration

**Comment by sjdirect** [comment] 2015-12-21 01:34
Thanks for the pictures of the stacktrace. It at least gave me an idea of what might be wrong. 

I just updated AbotX to 1.0.25 and the [sample project](https://github.com/sjdirect/abotx-basic-demo). Please try it and let me know you are still having the same issue.

**Comment by Hajuddin** [comment] 2015-12-22 07:21
Hi Steven,

Thank you. The sample project worked. I will give a try with parallel engine. Will keep you posted with the update.

Cheers
Minhaj

**Comment by sjdirect** [comment] 2015-12-22 21:40
Great to hear that. This is related to https://github.com/dnauck/Portable.Licensing/issues/26#issuecomment-166155341.

**Comment by sjdirect** [comment] 2016-01-14 06:15
Haven't heard any more of this issue

**Closed by sjdirect** 2016-01-14 06:15 UTC
